### Application ###
spring:
  application:
    name: customer-api
  profiles:
    active: dev
  security:
    user:
      name: "admin"
      password: "admin"
      roles:
        - ENDPOINT_ADMIN

### Actuator ###
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
