### Application ###
spring:
  application:
    name: customer-api
  profiles:
    active: dev
  security:
    user:
      name: "admin"
      password: "admin"
      roles:
        - ENDPOINT_ADMIN
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:simpledb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

### Actuator ###
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
